theme: jekyll-theme-minimal
title: Sandeep's homepage
description: Bookmark this to keep an eye on my project updates!
domain: sandeepgupta.github.io
url: https://sandeepgupta.github.io
baseurl: my-site